---
title: "map_making"
author: "willow_liu"
date: "12/7/2021"
output: html_document
---
### raster and vector
#1. read spatial data and reproject it
osm<-st_read(here::here())%>%
  st_transform(., 27700)%>%
#2. select attibute
filter(fclass=='hotel')
#3. read in csv and make it into spatial data
Airbnb<-read_csv()%>%
  st_as_sf(., coords=c("longitude", "Latitude"),crs = 4326) %>%
  st_transform(., 27700)
#4. select

#5. make a function for join

Joinfun <- function(data1,data2){

output<-data1%>%
 st_join(Londonborough,.)%>%
 add_count(GSS_CODE, name="hotels_in_borough")
 
 return(output)
}

#6. use the function!
Hotels <- Joinfun(OSM, Londonborough)

Airbnb <- Joinfun(Airbnb, Londonborough)

Worldcities2 <- Worldcities %>%
  filter(CNTRY_NAME=='United Kingdom'&
           Worldcities$CITY_NAME=='Birmingham'|
           Worldcities$CITY_NAME=='London'|
           Worldcities$CITY_NAME=='Edinburgh')

#7. plot the map
tm1<- tm_shape()+tm_polygons()+tm_legend+tm_layout+tm_credits()
tm2
tm3

tm_credits:文本注释

legend <- tm_shape(Hotels) + tm_polygons()
+tm_scale_bar+tm_layout+tm_compass+ tm..

t<-tmap_arrange(tm1,tm2,tm3,legend,ncol=2)

#8. inset the map 镶嵌式地图

1. st_bbox
2. st_as_sfc()
3. 做出main图
4. 做出inset的图
5. library(grid)
   main
   print(inset, vp = viewport)
   
#9. export map
tmap_save(t, 'png')

tmap_save(main, inset_tm=, inset_vp=, filename="", dpi=600)

#10 interactive map
library(leafpop)
library(leaflet)

1. Join data

Joined <- Airbnb %>%
  st_join(., Hotels, join=st_equals)%>%
  dyplyr::select
  dyplyr::rename
  st_transform
  
2. remove geometry for pop up boxes
st_drop_geometry

3. set the colour palettes using our previously defined breaks
colorBin()

4.add basemap options
5. add our polygons, linking to the tables we just made


  




